name: CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name1: src\ComponentSamplesBeingReferenced.sln
      Solution_Name2: src\ComponentSamples.sln
      Configuration: ${{ matrix.configuration }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - uses: actions/setup-dotnet@v4
    - uses: nuget/setup-nuget@v2
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Restore
      run: |
        msbuild $env:Solution_Name1 /t:Restore /p:Configuration=$env:Configuration
        msbuild $env:Solution_Name2 /t:Restore /p:Configuration=$env:Configuration

    - name: Build
      shell: powershell
      run: |
        $null = New-Item bld -ItemType Directory -Force
        msbuild $env:Solution_Name1 /t:Build /p:Configuration=$env:Configuration
        msbuild $env:Solution_Name2 /t:Build /p:Configuration=$env:Configuration | % {
          Write-Host $_
          $_ | Select-String '(?<project>\w+) -> (?<outputpath>.+)$' | % {
            [pscustomobject]@{
              Project   = $_.Matches[0].Groups['project'].Value
              Directory = ([io.fileinfo]$_.Matches[0].Groups['outputpath'].Value).DirectoryName
            }
          }
        } | Export-Csv bld\projects.csv -NoTypeInformation

    - name: Compress assets
      if: startsWith(github.ref, 'refs/tags/v')
      shell: powershell
      run: |
        $assetsDir = New-Item $PWD\bld\assets -ItemType Directory -Force

        Import-Csv bld\projects.csv | % {
          $debugTag = if ($env:Configuration -eq 'Debug') {'-debug'} else {''}
          $dest = '{0}-{1}-x64{2}.zip' -f (Join-Path $assetsDir $_.Project), $env:TAG, $debugTag
          Get-ChildItem $_.Directory | Compress-Archive -DestinationPath $dest
        }
      env:
        TAG: ${{ github.ref_name }}

    - name: Upload ${{ matrix.configuration }} artifacts
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration }}
        path: .\bld\assets\

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      
      - name: Create release
        run: gh release create ${{ github.ref_name }} --generate-notes --draft ./*.zip
        env:
          GH_TOKEN: ${{ github.token }}
